### ISSUE TITLE
Adicione mais dados

### ISSUE THREAD

**Issue by ramonpaolo** [juliobaccin/JavaScript-HoradeCodar#1]
Adicione um 'about', como esse:
![image](https://user-images.githubusercontent.com/53312850/173177006-403755e9-583f-4815-a3f4-7bc5b496f074.png)
Assim você dará um contextozinho, sobre o projeto : )

Tente também, adicionar as tecnologias envolvidas no projeto, como: HTML, CSS, JS e Git, como também descrito no print acima.

No `README.md` do projeto, ao invés de adicionar a imagem da capa do vídeo no qual você fez o 'curso', tente fazer um 'gif' de algum exercício que você achou bem bacana, e coloque ele no lugar da imagem, como eu fiz nesse [projeto](https://github.com/ramonpaolo/cripto-finance-tracker-app).

Qualquer dúvida, só me chamar 👍🏼

**Comment by juliobaccin** [comment]
Top, não havia pensando nisso, realmente fica muito melhor, vou ver pra atualizar, muito obrigado.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Ramon Paolo Maran ***@***.***>
Sent: Saturday, June 11, 2022 3:56:29 AM
To: juliobaccin/JavaScript-HoradeCodar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [juliobaccin/JavaScript-HoradeCodar] Adicione mais dados (Issue #1)


Adicione um 'about', como esse:
[image]<https://user-images.githubusercontent.com/53312850/173177006-403755e9-583f-4815-a3f4-7bc5b496f074.png>
Assim você dará um contextozinho, sobre o projeto : )

Tente também, adicionar as tecnologias envolvidas no projeto, como: HTML, CSS, JS e Git, como também descrito no print acima.

No README.md do projeto, ao invés de adicionar a imagem da capa do vídeo no qual você fez o 'curso', tente fazer um 'gif' de algum exercício que você achou bem bacana, e coloque ele no lugar da imagem, como eu fiz nesse projeto<https://github.com/ramonpaolo/cripto-finance-tracker-app>.

Qualquer dúvida, só me chamar 👍🏼
